"""Calibos' private workspace: the same subjective records, a kinder view.

Two changes over the stock SubjectiveWorkspace, both learned from live runs:

1. Pinned roots. Records generated by the cartridge (identity, values,
   boundaries, seeded preferences) are always included first, so a strong
   thought loop can no longer crowd the self out of its own view.
2. Deduplication. Repeated identical experiences (the same memory resurfacing
   three times, a thought echoed verbatim) keep only their earliest kept
   occurrence, and runaway thought chains are capped, so the 16-slot window
   stays diverse.

The view contract is unchanged: immutable (source, first_person) pairs, no
telemetry, no world authority.
"""
from __future__ import annotations

from jelly_psiduck.workspace import CognitiveView, FeltExperience, SubjectiveWorkspace

VIEW_LIMIT = 16
MAX_PINNED = 6
MAX_THOUGHTS = 5


class CalibosWorkspace(SubjectiveWorkspace):
    def view(self) -> CognitiveView:
        eligible = [r for r in self.records if r.available_to_cognition]

        pinned = [r for r in eligible if r.generated_by == "cartridge"][:MAX_PINNED]
        pinned_ids = {r.id for r in pinned}

        rest = [r for r in eligible if r.id not in pinned_ids]
        # Dedupe: keep the earliest occurrence of each (source, text) pair.
        seen: set[tuple[str, str]] = set()
        deduped = []
        for r in rest:
            key = (r.source, r.first_person)
            if key in seen:
                continue
            seen.add(key)
            deduped.append(r)

        # Cap runaway thought chains; keep the most recent ones.
        thoughts = [r for r in deduped if r.source == "thought"]
        drop = {r.id for r in thoughts[:-MAX_THOUGHTS]} if len(thoughts) > MAX_THOUGHTS else set()
        kept = [r for r in deduped if r.id not in drop]

        # Recency for the unpinned remainder; pinned roots always survive.
        room = VIEW_LIMIT - len(pinned)
        window = pinned + kept[-room:] if room > 0 else pinned[:VIEW_LIMIT]
        return CognitiveView(tuple(FeltExperience(r.source, r.first_person) for r in window))
