"""Calibos' private workspace: the same subjective records, a kinder view.

Four changes over the stock SubjectiveWorkspace, all learned from live runs:

1. Pinned roots. Records generated by the cartridge (identity, values,
   boundaries, seeded preferences) are always included first, so a strong
   thought loop can no longer crowd the self out of its own view.
2. Near-duplicate dedupe. Token-set Jaccard similarity generalizes the old
   exact (source, text) dedupe: the observed failure was a memory resurfacing
   with slightly different wording slipping past exact match. Above the
   similarity threshold only one representative per duplicate set survives —
   the most salient when ranked by salience, the earliest when ranked by
   recency. Very short texts are exempt: their Jaccard scores are too noisy.
3. Per-class caps. Each record class (memory, thought, perception, ...)
   gets a ceiling on the unpinned window, so a single class — a repeated
   memory resurfacing, a runaway thought loop — can no longer dominate the
   view. Caps are hard ceilings: a saturated class yields a smaller window,
   not a dominated one. Pinned roots are exempt by design. This supersedes
   the old thought-chain cap, which was the same idea applied to one class.
4. Salience ranking. The unpinned remainder is ordered by retrieval salience
   (ACT-R-style activation from recency + rehearsal, lifted by engaged
   importance, penalized for unengaged surfacings, boosted for unresolved
   concerns) instead of pure recency. Computed lazily at view time; nothing
   is ever deleted or mutated for ranking.

The view contract is unchanged: immutable (source, first_person) pairs, no
telemetry, no world authority. All new logic is deterministic, zero models,
zero new state.
"""
from __future__ import annotations

import re
from dataclasses import FrozenInstanceError

from jelly_psiduck.workspace import CognitiveView, FeltExperience, SubjectiveWorkspace

from .consolidate import excluded_ids
from .unresolved import has_unresolved_links


class _ViewWithIds(CognitiveView):
    """A CognitiveView carrying the record ids behind its experiences.

    The frozen engine's FeltExperience carries no record id, so a provider
    that only sees the view cannot join prompt experiences back to the
    records that surfaced — which ``mind answer --silent`` needs when view
    substitution re-rendered an experience's text (felt != true). The ids
    travel WITH the view, positionally: ``record_ids[i]`` is the record
    behind ``experiences[i]``.

    ``record_ids`` is deliberately NOT a dataclass field:
    ``dataclasses.asdict()`` (which ``cognitive_prompt`` uses to render the
    prompt text the thinker sees) only serializes declared fields, so the
    ids can never leak into prompt text, displays, or recall — the same
    private-provenance distinction as dream fragments. Binding the ids to
    the view object also makes them immune to the stale-side-channel
    hazard by construction: there is no cross-object temporal coupling for
    a later ``think()`` to get wrong.

    Readers must fail closed on length mismatch: omit the ids, never
    misattribute.
    """

    __slots__ = ("record_ids",)

    def __setattr__(self, name, value):
        # Frozen like the base: the base's generated __setattr__ misfires
        # on subclass instances (it closes over the pre-slots class), so
        # enforce immutability explicitly.
        raise FrozenInstanceError(
            f"cannot assign to field {name!r}: view-carried provenance is immutable")


def _view_with_ids(experiences, ids):
    """Build a _ViewWithIds without tripping the frozen __setattr__."""
    view = _ViewWithIds.__new__(_ViewWithIds)
    object.__setattr__(view, "experiences", tuple(experiences))
    object.__setattr__(view, "record_ids", tuple(ids))
    return view

VIEW_LIMIT = 16
MAX_PINNED = 6

# Near-duplicate cutoff: token-set Jaccard over lowercased word tokens.
JACCARD_DUP_THRESHOLD = 0.85
# A similarity verdict needs enough material; below this union size the
# score is noise, so short texts (a three-word interoception) are exempt.
MIN_DUP_TOKENS = 6

# Per-class ceilings on the unpinned window. Ceilings, not quotas.
CLASS_CAPS = {
    "thought": 4,
    "memory": 4,
    "perception": 3,
    "interoception": 2,
    "temporal": 2,
    "imagination": 2,
    "social": 3,
    "action_consequence": 2,
}
DEFAULT_CLASS_CAP = 3

_WORD_RE = re.compile(r"\w+")


def _tokens(text: str) -> frozenset[str]:
    return frozenset(_WORD_RE.findall(text.lower()))


def _near_duplicate(a: frozenset[str], b: frozenset[str]) -> bool:
    union = a | b
    if len(union) < MIN_DUP_TOKENS:
        return False
    return len(a & b) / len(union) >= JACCARD_DUP_THRESHOLD


class CalibosWorkspace(SubjectiveWorkspace):
    # Attached by CalibosSubject when a salience sidecar path is configured.
    # Absent (plain engine use) -> falls back to recency ordering.
    salience_tracker = None
    # Transient provenance side-channel (in-memory only, never persisted):
    # the record ids behind the most recently built view, in order. The
    # frozen engine's FeltExperience drops the record id, so a recorder that
    # only sees the view cannot recover provenance without this. Set on every
    # view() call; read synchronously by DreamCognition.think() via the
    # resolver wired in cmd_dream. Never rendered into prompts or displays.
    #
    # LOAD-BEARING SYNCHRONICITY ASSUMPTION: this side-channel is trustworthy
    # ONLY while workspace-view construction and provider invocation remain
    # synchronous and single-view. Correctness rests on the strict event
    # order view()->think()->view()->think(), with the resolver read at
    # think entry seeing exactly the view built immediately before it (pinned
    # by the event-order test in tests/adversarial/
    # test_critic_dream_provenance_r1.py). A future change breaks it if it
    # introduces async or concurrent think() calls (the resolver can read a
    # racing view's ids), buffered or deferred cognition (a view consumed
    # after its successor was built), or ANY view() rebuild before the
    # provider consumes the previous view. If that changes, provenance must
    # travel on the view itself (record_ids, already carried by
    # _ViewWithIds and staleness-proof) instead of this side-channel.
    _last_view_ids: tuple = ()
    # Callable returning the set of currently-unresolved link keys (see
    # calibos_mind/unresolved.py). Attached by CalibosSubject from live engine
    # state so the Zeigarnik boost intersects links against what is actually
    # open. None -> the shared helper falls back to the legacy any-link check.
    open_keys_provider = None
    # Path to the consolidation availability journal (archive/availability.json).
    # Records listed there are archived: history, never deleted, but excluded
    # from cognition views. None -> no exclusions (e.g. plain engine use).
    availability_path = None
    # Attached by CalibosSubject when an interoception sidecar path is
    # configured. None -> interoception records pass through untouched.
    interoception_tracker = None

    def _view_experience(self, r):
        """FeltExperience for a record, with the interoceptive-gap substitution.

        Body-derived interoception records are re-rendered from FELT urgency
        (see calibos_mind/interoception.py): the thinker meets the felt body,
        not the actual one. This is the last step of view construction —
        record ids, salience, intensity, ordering, caps, dedupe, and archive
        exclusions are all computed on the true records first, untouched.
        """
        tracker = self.interoception_tracker
        if tracker is not None and r.source == "interoception":
            text = tracker.text_for_record(r)
            if text is not None:
                return FeltExperience(r.source, text)
        return FeltExperience(r.source, r.first_person)

    def view(self) -> CognitiveView:
        archived = (excluded_ids(self.availability_path)
                    if self.availability_path else frozenset())
        eligible = [r for r in self.records
                    if r.available_to_cognition and r.id not in archived]

        pinned = [r for r in eligible if r.generated_by == "cartridge"][:MAX_PINNED]
        pinned_ids = {r.id for r in pinned}

        rest = [r for r in eligible if r.id not in pinned_ids]
        room = VIEW_LIMIT - len(pinned)
        if room <= 0:
            ids = tuple(r.id for r in pinned[:VIEW_LIMIT])
            self._last_view_ids = ids
            return _view_with_ids(
                tuple(self._view_experience(r) for r in pinned[:VIEW_LIMIT]),
                ids)

        tracker = self.salience_tracker
        if tracker is not None:
            provider = self.open_keys_provider
            open_keys = provider() if provider is not None else None
            now_tick = max((r.tick for r in rest), default=0)
            ranked = sorted(
                rest,
                key=lambda r: (tracker.activation(
                    r.id, r.tick, now_tick,
                    unresolved=has_unresolved_links(
                        r.concern_links, r.expectation_links, open_keys),
                ), r.tick),
                reverse=True,
            )
        else:
            # No tracker: newest first for selection, matching the stock view's
            # recency bias; the window is re-chronologized before return.
            ranked = sorted(rest, key=lambda r: r.tick, reverse=True)

        deduped = self._dedupe(ranked)
        admitted = self._fill_capped(deduped, room)
        if tracker is None:
            admitted = admitted[::-1]
        window = pinned + admitted
        # Provenance side-channel: capture the record ids behind this view,
        # in order, before the FeltExperience conversion drops them. The
        # engine hands the provider the freshly built view immediately, so a
        # resolver reading this inside think() sees exactly this view's ids.
        # The ids ALSO travel on the view itself (record_ids), so a provider
        # that only ever sees the view can still join experiences to
        # records — staleness-proof, no temporal coupling.
        self._last_view_ids = tuple(r.id for r in window)
        return _view_with_ids(
            tuple(self._view_experience(r) for r in window),
            self._last_view_ids)

    def _dedupe(self, ranked):
        """Drop exact and near-duplicate texts, same source only.

        The first survivor in rank order wins: the most salient record when
        salience-ranked, the most recent when ranked by recency. Pinned roots
        are handled before this and are never deduped against.
        """
        seen_exact: set[tuple[str, str]] = set()
        kept_texts: dict[str, list[frozenset[str]]] = {}
        out = []
        for r in ranked:
            key = (r.source, r.first_person)
            if key in seen_exact:
                continue
            toks = _tokens(r.first_person)
            if any(_near_duplicate(toks, prev) for prev in kept_texts.get(r.source, ())):
                continue
            seen_exact.add(key)
            kept_texts.setdefault(r.source, []).append(toks)
            out.append(r)
        return out

    def _fill_capped(self, ranked, room):
        """Admit up to `room` records, honoring per-class ceilings.

        Hard ceilings: once a class is full, further records of that class
        are skipped and the window simply ends up smaller. No backfill —
        refilling with the skipped records would re-saturate the view.
        """
        admitted = []
        counts: dict[str, int] = {}
        for r in ranked:
            cap = CLASS_CAPS.get(r.source, DEFAULT_CLASS_CAP)
            if counts.get(r.source, 0) >= cap:
                continue
            admitted.append(r)
            counts[r.source] = counts.get(r.source, 0) + 1
            if len(admitted) >= room:
                break
        return admitted
